    //
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 09:54:00 PM CET 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metadata" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="BrojPrijave" type="{http://www.w3.org/2001/XMLSchema}ID"/>
 *         &lt;element name="DatumPrijema" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DatumPodnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="NazivPronalaskaSrb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NazivPronalaskaEng" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PodnosilacPrijave" type="{}TOsoba"/>
 *         &lt;element name="PodnosilacFaks" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Drzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OstaliPodnosioci" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Pronalazac" type="{}TOsoba"/>
 *         &lt;element name="PronalazacFaks" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OstaliPronalazaci" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="AdresaZaDostavljanje" type="{}TAdresa"/>
 *         &lt;element name="NacinDostave" type="{}TNacinDostave"/>
 *         &lt;element name="RanijePrijave" type="{}TRanijePrijave"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "brojPrijave",
    "datumPrijema",
    "datumPodnosenja",
    "nazivPronalaskaSrb",
    "nazivPronalaskaEng",
    "podnosilacPrijave",
    "podnosilacFaks",
    "drzavljanstvo",
    "ostaliPodnosioci",
    "pronalazac",
    "pronalazacFaks",
    "ostaliPronalazaci",
    "adresaZaDostavljanje",
    "nacinDostave",
    "ranijePrijave"
})
@XmlRootElement(name = "Patent")
public class Patent {

    @XmlElement(required = true)
    protected Object metadata;
    @XmlElement(name = "BrojPrijave", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String brojPrijave;
    @XmlElement(name = "DatumPrijema", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPrijema;
    @XmlElement(name = "DatumPodnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;
    @XmlElement(name = "NazivPronalaskaSrb", required = true)
    protected String nazivPronalaskaSrb;
    @XmlElement(name = "NazivPronalaskaEng", required = true)
    protected String nazivPronalaskaEng;
    @XmlElement(name = "PodnosilacPrijave", required = true)
    protected TOsoba podnosilacPrijave;
    @XmlElement(name = "PodnosilacFaks")
    protected int podnosilacFaks;
    @XmlElement(name = "Drzavljanstvo", required = true)
    protected String drzavljanstvo;
    @XmlElement(name = "OstaliPodnosioci")
    protected boolean ostaliPodnosioci;
    @XmlElement(name = "Pronalazac", required = true)
    protected TOsoba pronalazac;
    @XmlElement(name = "PronalazacFaks")
    protected int pronalazacFaks;
    @XmlElement(name = "OstaliPronalazaci")
    protected boolean ostaliPronalazaci;
    @XmlElement(name = "AdresaZaDostavljanje", required = true)
    protected TAdresa adresaZaDostavljanje;
    @XmlElement(name = "NacinDostave", required = true)
    protected TNacinDostave nacinDostave;
    @XmlElement(name = "RanijePrijave", required = true)
    protected TRanijePrijave ranijePrijave;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMetadata(Object value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the brojPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPrijave() {
        return brojPrijave;
    }

    /**
     * Sets the value of the brojPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPrijave(String value) {
        this.brojPrijave = value;
    }

    /**
     * Gets the value of the datumPrijema property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPrijema() {
        return datumPrijema;
    }

    /**
     * Sets the value of the datumPrijema property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPrijema(XMLGregorianCalendar value) {
        this.datumPrijema = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

    /**
     * Gets the value of the nazivPronalaskaSrb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivPronalaskaSrb() {
        return nazivPronalaskaSrb;
    }

    /**
     * Sets the value of the nazivPronalaskaSrb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivPronalaskaSrb(String value) {
        this.nazivPronalaskaSrb = value;
    }

    /**
     * Gets the value of the nazivPronalaskaEng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivPronalaskaEng() {
        return nazivPronalaskaEng;
    }

    /**
     * Sets the value of the nazivPronalaskaEng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivPronalaskaEng(String value) {
        this.nazivPronalaskaEng = value;
    }

    /**
     * Gets the value of the podnosilacPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link TOsoba }
     *     
     */
    public TOsoba getPodnosilacPrijave() {
        return podnosilacPrijave;
    }

    /**
     * Sets the value of the podnosilacPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsoba }
     *     
     */
    public void setPodnosilacPrijave(TOsoba value) {
        this.podnosilacPrijave = value;
    }

    /**
     * Gets the value of the podnosilacFaks property.
     * 
     */
    public int getPodnosilacFaks() {
        return podnosilacFaks;
    }

    /**
     * Sets the value of the podnosilacFaks property.
     * 
     */
    public void setPodnosilacFaks(int value) {
        this.podnosilacFaks = value;
    }

    /**
     * Gets the value of the drzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrzavljanstvo(String value) {
        this.drzavljanstvo = value;
    }

    /**
     * Gets the value of the ostaliPodnosioci property.
     * 
     */
    public boolean isOstaliPodnosioci() {
        return ostaliPodnosioci;
    }

    /**
     * Sets the value of the ostaliPodnosioci property.
     * 
     */
    public void setOstaliPodnosioci(boolean value) {
        this.ostaliPodnosioci = value;
    }

    /**
     * Gets the value of the pronalazac property.
     * 
     * @return
     *     possible object is
     *     {@link TOsoba }
     *     
     */
    public TOsoba getPronalazac() {
        return pronalazac;
    }

    /**
     * Sets the value of the pronalazac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsoba }
     *     
     */
    public void setPronalazac(TOsoba value) {
        this.pronalazac = value;
    }

    /**
     * Gets the value of the pronalazacFaks property.
     * 
     */
    public int getPronalazacFaks() {
        return pronalazacFaks;
    }

    /**
     * Sets the value of the pronalazacFaks property.
     * 
     */
    public void setPronalazacFaks(int value) {
        this.pronalazacFaks = value;
    }

    /**
     * Gets the value of the ostaliPronalazaci property.
     * 
     */
    public boolean isOstaliPronalazaci() {
        return ostaliPronalazaci;
    }

    /**
     * Sets the value of the ostaliPronalazaci property.
     * 
     */
    public void setOstaliPronalazaci(boolean value) {
        this.ostaliPronalazaci = value;
    }

    /**
     * Gets the value of the adresaZaDostavljanje property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresa }
     *     
     */
    public TAdresa getAdresaZaDostavljanje() {
        return adresaZaDostavljanje;
    }

    /**
     * Sets the value of the adresaZaDostavljanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresa }
     *     
     */
    public void setAdresaZaDostavljanje(TAdresa value) {
        this.adresaZaDostavljanje = value;
    }

    /**
     * Gets the value of the nacinDostave property.
     * 
     * @return
     *     possible object is
     *     {@link TNacinDostave }
     *     
     */
    public TNacinDostave getNacinDostave() {
        return nacinDostave;
    }

    /**
     * Sets the value of the nacinDostave property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNacinDostave }
     *     
     */
    public void setNacinDostave(TNacinDostave value) {
        this.nacinDostave = value;
    }

    /**
     * Gets the value of the ranijePrijave property.
     * 
     * @return
     *     possible object is
     *     {@link TRanijePrijave }
     *     
     */
    public TRanijePrijave getRanijePrijave() {
        return ranijePrijave;
    }

    /**
     * Sets the value of the ranijePrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRanijePrijave }
     *     
     */
    public void setRanijePrijave(TRanijePrijave value) {
        this.ranijePrijave = value;
    }

}
