//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 09:54:00 PM CET 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TPunomocnik complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPunomocnik">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Zastupanje" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="PrijemPismena" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ZajednickiPredstavnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPunomocnik", propOrder = {
    "zastupanje",
    "prijemPismena",
    "zajednickiPredstavnik"
})
public class TPunomocnik {

    @XmlElement(name = "Zastupanje")
    protected Boolean zastupanje;
    @XmlElement(name = "PrijemPismena")
    protected Boolean prijemPismena;
    @XmlElement(name = "ZajednickiPredstavnik")
    protected Boolean zajednickiPredstavnik;

    /**
     * Gets the value of the zastupanje property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isZastupanje() {
        return zastupanje;
    }

    /**
     * Sets the value of the zastupanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setZastupanje(Boolean value) {
        this.zastupanje = value;
    }

    /**
     * Gets the value of the prijemPismena property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrijemPismena() {
        return prijemPismena;
    }

    /**
     * Sets the value of the prijemPismena property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrijemPismena(Boolean value) {
        this.prijemPismena = value;
    }

    /**
     * Gets the value of the zajednickiPredstavnik property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isZajednickiPredstavnik() {
        return zajednickiPredstavnik;
    }

    /**
     * Sets the value of the zajednickiPredstavnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setZajednickiPredstavnik(Boolean value) {
        this.zajednickiPredstavnik = value;
    }

}
