//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 07:06:46 PM CET 
//


package model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevAutorskaPrava }
     * 
     */
    public ZahtevAutorskaPrava createZahtevAutorskaPrava() {
        return new ZahtevAutorskaPrava();
    }

    /**
     * Create an instance of {@link ZahtevAutorskaPrava.AutoriIliKoauori }
     * 
     */
    public ZahtevAutorskaPrava.AutoriIliKoauori createZahtevAutorskaPravaAutoriIliKoauori() {
        return new ZahtevAutorskaPrava.AutoriIliKoauori();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link ZahtevAutorskaPrava.PravnoLice }
     * 
     */
    public ZahtevAutorskaPrava.PravnoLice createZahtevAutorskaPravaPravnoLice() {
        return new ZahtevAutorskaPrava.PravnoLice();
    }

    /**
     * Create an instance of {@link TPodnosilac }
     * 
     */
    public TPodnosilac createTPodnosilac() {
        return new TPodnosilac();
    }

    /**
     * Create an instance of {@link ZahtevAutorskaPrava.PriloziUzPrijavu }
     * 
     */
    public ZahtevAutorskaPrava.PriloziUzPrijavu createZahtevAutorskaPravaPriloziUzPrijavu() {
        return new ZahtevAutorskaPrava.PriloziUzPrijavu();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TNZAutor }
     * 
     */
    public TNZAutor createTNZAutor() {
        return new TNZAutor();
    }

    /**
     * Create an instance of {@link ZahtevAutorskaPrava.AutoriIliKoauori.Autori }
     * 
     */
    public ZahtevAutorskaPrava.AutoriIliKoauori.Autori createZahtevAutorskaPravaAutoriIliKoauoriAutori() {
        return new ZahtevAutorskaPrava.AutoriIliKoauori.Autori();
    }

    /**
     * Create an instance of {@link ZahtevAutorskaPrava.AutoriIliKoauori.NisuZiviAutori }
     * 
     */
    public ZahtevAutorskaPrava.AutoriIliKoauori.NisuZiviAutori createZahtevAutorskaPravaAutoriIliKoauoriNisuZiviAutori() {
        return new ZahtevAutorskaPrava.AutoriIliKoauori.NisuZiviAutori();
    }

}
