//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.11 at 07:06:46 PM CET 
//


package model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Metadata" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Fizicko_lice" type="{}TFizicko_lice"/>
 *         &lt;element name="Pravno_lice">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Sediste" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Telefon" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Pseudonim_autora" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Punomocnik" type="{}TPodnosilac"/>
 *         &lt;element name="Naslov_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Podaci_o_naslovu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Vrsta_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Forma_zapisa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Autori_ili_koauori">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Autori">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Autor" type="{}TFizicko_lice" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Nisu_zivi_autori">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NZ_autor" type="{}TNZ_autor" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Anoniman_autor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Radni_odnos" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Nacin_koriscenja_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Prilozi_uz_prijavu">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Opis_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Primer_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Broj_prijave">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\p{L}-\d{1,100000}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "fizickoLice",
    "pravnoLice",
    "telefon",
    "email",
    "pseudonimAutora",
    "punomocnik",
    "naslovAutorskogDela",
    "podaciONaslovu",
    "vrstaAutorskogDela",
    "formaZapisa",
    "autoriIliKoauori",
    "radniOdnos",
    "nacinKoriscenjaDela",
    "potpis",
    "priloziUzPrijavu",
    "brojPrijave",
    "datumPodnosenja"
})
@XmlRootElement(name = "Zahtev_autorska_prava")
public class ZahtevAutorskaPrava {

    @XmlElement(name = "Metadata", required = true)
    protected String metadata;
    @XmlElement(name = "Fizicko_lice", required = true)
    protected TFizickoLice fizickoLice;
    @XmlElement(name = "Pravno_lice", required = true)
    protected ZahtevAutorskaPrava.PravnoLice pravnoLice;
    @XmlElement(name = "Telefon")
    protected int telefon;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "Pseudonim_autora", required = true, nillable = true)
    protected String pseudonimAutora;
    @XmlElement(name = "Punomocnik", required = true, nillable = true)
    protected TPodnosilac punomocnik;
    @XmlElement(name = "Naslov_autorskog_dela", required = true)
    protected String naslovAutorskogDela;
    @XmlElement(name = "Podaci_o_naslovu", required = true)
    protected String podaciONaslovu;
    @XmlElement(name = "Vrsta_autorskog_dela", required = true)
    protected String vrstaAutorskogDela;
    @XmlElement(name = "Forma_zapisa", required = true)
    protected String formaZapisa;
    @XmlElement(name = "Autori_ili_koauori", required = true)
    protected ZahtevAutorskaPrava.AutoriIliKoauori autoriIliKoauori;
    @XmlElement(name = "Radni_odnos", required = true)
    protected String radniOdnos;
    @XmlElement(name = "Nacin_koriscenja_dela", required = true)
    protected String nacinKoriscenjaDela;
    @XmlElement(name = "Potpis", required = true)
    protected String potpis;
    @XmlElement(name = "Prilozi_uz_prijavu", required = true)
    protected ZahtevAutorskaPrava.PriloziUzPrijavu priloziUzPrijavu;
    @XmlElement(name = "Broj_prijave", required = true, defaultValue = "A-1")
    protected String brojPrijave;
    @XmlElement(name = "Datum_podnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadata(String value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the fizickoLice property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getFizickoLice() {
        return fizickoLice;
    }

    /**
     * Sets the value of the fizickoLice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setFizickoLice(TFizickoLice value) {
        this.fizickoLice = value;
    }

    /**
     * Gets the value of the pravnoLice property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevAutorskaPrava.PravnoLice }
     *     
     */
    public ZahtevAutorskaPrava.PravnoLice getPravnoLice() {
        return pravnoLice;
    }

    /**
     * Sets the value of the pravnoLice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevAutorskaPrava.PravnoLice }
     *     
     */
    public void setPravnoLice(ZahtevAutorskaPrava.PravnoLice value) {
        this.pravnoLice = value;
    }

    /**
     * Gets the value of the telefon property.
     * 
     */
    public int getTelefon() {
        return telefon;
    }

    /**
     * Sets the value of the telefon property.
     * 
     */
    public void setTelefon(int value) {
        this.telefon = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the pseudonimAutora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPseudonimAutora() {
        return pseudonimAutora;
    }

    /**
     * Sets the value of the pseudonimAutora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPseudonimAutora(String value) {
        this.pseudonimAutora = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link TPodnosilac }
     *     
     */
    public TPodnosilac getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPodnosilac }
     *     
     */
    public void setPunomocnik(TPodnosilac value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the naslovAutorskogDela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslovAutorskogDela() {
        return naslovAutorskogDela;
    }

    /**
     * Sets the value of the naslovAutorskogDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslovAutorskogDela(String value) {
        this.naslovAutorskogDela = value;
    }

    /**
     * Gets the value of the podaciONaslovu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodaciONaslovu() {
        return podaciONaslovu;
    }

    /**
     * Sets the value of the podaciONaslovu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodaciONaslovu(String value) {
        this.podaciONaslovu = value;
    }

    /**
     * Gets the value of the vrstaAutorskogDela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrstaAutorskogDela() {
        return vrstaAutorskogDela;
    }

    /**
     * Sets the value of the vrstaAutorskogDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrstaAutorskogDela(String value) {
        this.vrstaAutorskogDela = value;
    }

    /**
     * Gets the value of the formaZapisa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaZapisa() {
        return formaZapisa;
    }

    /**
     * Sets the value of the formaZapisa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaZapisa(String value) {
        this.formaZapisa = value;
    }

    /**
     * Gets the value of the autoriIliKoauori property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevAutorskaPrava.AutoriIliKoauori }
     *     
     */
    public ZahtevAutorskaPrava.AutoriIliKoauori getAutoriIliKoauori() {
        return autoriIliKoauori;
    }

    /**
     * Sets the value of the autoriIliKoauori property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevAutorskaPrava.AutoriIliKoauori }
     *     
     */
    public void setAutoriIliKoauori(ZahtevAutorskaPrava.AutoriIliKoauori value) {
        this.autoriIliKoauori = value;
    }

    /**
     * Gets the value of the radniOdnos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadniOdnos() {
        return radniOdnos;
    }

    /**
     * Sets the value of the radniOdnos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadniOdnos(String value) {
        this.radniOdnos = value;
    }

    /**
     * Gets the value of the nacinKoriscenjaDela property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacinKoriscenjaDela() {
        return nacinKoriscenjaDela;
    }

    /**
     * Sets the value of the nacinKoriscenjaDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacinKoriscenjaDela(String value) {
        this.nacinKoriscenjaDela = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpis(String value) {
        this.potpis = value;
    }

    /**
     * Gets the value of the priloziUzPrijavu property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevAutorskaPrava.PriloziUzPrijavu }
     *     
     */
    public ZahtevAutorskaPrava.PriloziUzPrijavu getPriloziUzPrijavu() {
        return priloziUzPrijavu;
    }

    /**
     * Sets the value of the priloziUzPrijavu property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevAutorskaPrava.PriloziUzPrijavu }
     *     
     */
    public void setPriloziUzPrijavu(ZahtevAutorskaPrava.PriloziUzPrijavu value) {
        this.priloziUzPrijavu = value;
    }

    /**
     * Gets the value of the brojPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPrijave() {
        return brojPrijave;
    }

    /**
     * Sets the value of the brojPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPrijave(String value) {
        this.brojPrijave = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Autori">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Autor" type="{}TFizicko_lice" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Nisu_zivi_autori">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NZ_autor" type="{}TNZ_autor" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Anoniman_autor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "autori",
        "nisuZiviAutori",
        "anonimanAutor"
    })
    public static class AutoriIliKoauori {

        @XmlElement(name = "Autori")
        protected ZahtevAutorskaPrava.AutoriIliKoauori.Autori autori;
        @XmlElement(name = "Nisu_zivi_autori")
        protected ZahtevAutorskaPrava.AutoriIliKoauori.NisuZiviAutori nisuZiviAutori;
        @XmlElement(name = "Anoniman_autor")
        protected String anonimanAutor;

        /**
         * Gets the value of the autori property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevAutorskaPrava.AutoriIliKoauori.Autori }
         *     
         */
        public ZahtevAutorskaPrava.AutoriIliKoauori.Autori getAutori() {
            return autori;
        }

        /**
         * Sets the value of the autori property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevAutorskaPrava.AutoriIliKoauori.Autori }
         *     
         */
        public void setAutori(ZahtevAutorskaPrava.AutoriIliKoauori.Autori value) {
            this.autori = value;
        }

        /**
         * Gets the value of the nisuZiviAutori property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevAutorskaPrava.AutoriIliKoauori.NisuZiviAutori }
         *     
         */
        public ZahtevAutorskaPrava.AutoriIliKoauori.NisuZiviAutori getNisuZiviAutori() {
            return nisuZiviAutori;
        }

        /**
         * Sets the value of the nisuZiviAutori property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevAutorskaPrava.AutoriIliKoauori.NisuZiviAutori }
         *     
         */
        public void setNisuZiviAutori(ZahtevAutorskaPrava.AutoriIliKoauori.NisuZiviAutori value) {
            this.nisuZiviAutori = value;
        }

        /**
         * Gets the value of the anonimanAutor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnonimanAutor() {
            return anonimanAutor;
        }

        /**
         * Sets the value of the anonimanAutor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnonimanAutor(String value) {
            this.anonimanAutor = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Autor" type="{}TFizicko_lice" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "autor"
        })
        public static class Autori {

            @XmlElement(name = "Autor", required = true)
            protected List<TFizickoLice> autor;

            /**
             * Gets the value of the autor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the autor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAutor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TFizickoLice }
             * 
             * 
             */
            public List<TFizickoLice> getAutor() {
                if (autor == null) {
                    autor = new ArrayList<TFizickoLice>();
                }
                return this.autor;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NZ_autor" type="{}TNZ_autor" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nzAutor"
        })
        public static class NisuZiviAutori {

            @XmlElement(name = "NZ_autor", required = true)
            protected List<TNZAutor> nzAutor;

            /**
             * Gets the value of the nzAutor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the nzAutor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getNZAutor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TNZAutor }
             * 
             * 
             */
            public List<TNZAutor> getNZAutor() {
                if (nzAutor == null) {
                    nzAutor = new ArrayList<TNZAutor>();
                }
                return this.nzAutor;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Sediste" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ime",
        "sediste"
    })
    public static class PravnoLice {

        @XmlElement(name = "Ime", required = true)
        protected String ime;
        @XmlElement(name = "Sediste", required = true)
        protected String sediste;

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the sediste property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSediste() {
            return sediste;
        }

        /**
         * Sets the value of the sediste property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSediste(String value) {
            this.sediste = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Opis_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Primer_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "opisDela",
        "primerAutorskogDela"
    })
    public static class PriloziUzPrijavu {

        @XmlElement(name = "Opis_dela", required = true)
        protected String opisDela;
        @XmlElement(name = "Primer_autorskog_dela", required = true)
        protected String primerAutorskogDela;

        /**
         * Gets the value of the opisDela property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpisDela() {
            return opisDela;
        }

        /**
         * Sets the value of the opisDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpisDela(String value) {
            this.opisDela = value;
        }

        /**
         * Gets the value of the primerAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimerAutorskogDela() {
            return primerAutorskogDela;
        }

        /**
         * Sets the value of the primerAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimerAutorskogDela(String value) {
            this.primerAutorskogDela = value;
        }

    }

}
